/*
  ============================================================================
  WEBHEAD PORTAL — reference firmware
  A tiny captive-portal appliance for the Seeed XIAO ESP32-S3 (and similar).
  It broadcasts an open Wi-Fi network, runs its own DNS (every name -> the
  board), serves the LittleFS payload (your webhead image's data/ folder), and
  gives a serial admin shell.

  You normally do NOT edit this file. `webhead build-image` bakes your image's
  identity in at compile time via -D flags:
      WH_SSID    the Wi-Fi network name        (default "Webhead")
      WH_DOMAIN  the site domain               (default "webhead.local")
  Everything else — the pages, games, certs — comes from LittleFS, so one
  firmware serves any image.
  ============================================================================
*/
#include <WiFi.h>
#include <DNSServer.h>
#include <WebServer.h>
#include <LittleFS.h>

// `webhead build-image` drops a wh_config.h next to this sketch with the image's
// SSID/domain. If it's absent (e.g. opened directly in the IDE), the defaults
// below are used.
#if defined(__has_include)
#  if __has_include("wh_config.h")
#    include "wh_config.h"
#  endif
#endif

#ifndef WH_SSID
#define WH_SSID "Webhead"
#endif
#ifndef WH_DOMAIN
#define WH_DOMAIN "webhead.local"
#endif

const char* AP_SSID   = WH_SSID;
const char* AP_PASS   = "";              // "" = open network
const char* MY_DOMAIN = WH_DOMAIN;
const int   MAX_CLIENTS = 8;
IPAddress   apIP(4, 3, 2, 1);
IPAddress   netMsk(255, 255, 255, 0);
const byte  DNS_PORT = 53;

DNSServer dnsServer;
WebServer http(80);

uint32_t bootMs = 0;
uint32_t hits = 0;

String contentType(const String& p) {
  if (p.endsWith(".html")) return "text/html";
  if (p.endsWith(".css"))  return "text/css";
  if (p.endsWith(".js"))   return "application/javascript";
  if (p.endsWith(".json")) return "application/json";
  if (p.endsWith(".svg"))  return "image/svg+xml";
  if (p.endsWith(".png"))  return "image/png";
  return "text/plain";
}

bool sendFile(String path) {
  if (path.endsWith("/")) path += "index.html";
  if (!LittleFS.exists(path)) return false;
  File f = LittleFS.open(path, "r");
  http.streamFile(f, contentType(path));
  f.close();
  hits++;
  return true;
}

void redirectPortal() {
  http.sendHeader("Location", String("http://") + apIP.toString() + "/", true);
  http.send(302, "text/plain", "");
}

void handleRoot()  { if (!sendFile("/index.html")) http.send(200, "text/html", "<h1>Webhead</h1><p>Upload a filesystem image.</p>"); }
void handleAdmin() { if (!sendFile("/admin.html")) http.send(404, "text/plain", "no admin.html"); }
void handleNotFound() {
  String uri = http.uri();
  if (sendFile(uri)) return;
  redirectPortal();               // captive-portal probes + unknown -> portal
}

// ---------------- serial admin shell ----------------
String line = "";
void prompt() { Serial.print("\nwebhead# "); }
void runCmd(String c) {
  c.trim();
  if (c == "help")        Serial.println("help status ls cat <f> free uptime clients reboot");
  else if (c == "status") { Serial.printf("ssid %s  domain %s  ip %s\nuptime %lus  clients %d  hits %u  heap %u KB\n",
                              AP_SSID, MY_DOMAIN, apIP.toString().c_str(), (millis()-bootMs)/1000,
                              WiFi.softAPgetStationNum(), hits, ESP.getFreeHeap()/1024); }
  else if (c == "clients")Serial.printf("%d connected\n", WiFi.softAPgetStationNum());
  else if (c == "free")   Serial.printf("heap %u KB\n", ESP.getFreeHeap()/1024);
  else if (c == "uptime") Serial.printf("%lus\n", (millis()-bootMs)/1000);
  else if (c.startsWith("ls")) { File d = LittleFS.open("/"); for (File f = d.openNextFile(); f; f = d.openNextFile()) Serial.printf("%8u  %s\n", (unsigned)f.size(), f.name()); }
  else if (c.startsWith("cat ")) { File f = LittleFS.open(c.substring(4)); if (f){ while (f.available()) Serial.write(f.read()); f.close(); Serial.println(); } else Serial.println("no such file"); }
  else if (c == "reboot") { Serial.println("rebooting..."); delay(200); ESP.restart(); }
  else if (c.length())    Serial.printf("unknown: %s\n", c.c_str());
}

void setup() {
  Serial.begin(115200);
  delay(300);
  if (!LittleFS.begin(true)) Serial.println("LittleFS mount failed — flash a filesystem image");
  bootMs = millis();

  WiFi.mode(WIFI_AP);
  WiFi.softAPConfig(apIP, apIP, netMsk);
  WiFi.softAP(AP_SSID, (strlen(AP_PASS) ? AP_PASS : NULL), 1, 0, MAX_CLIENTS);
  delay(300);

  dnsServer.setErrorReplyCode(DNSReplyCode::NoError);
  dnsServer.start(DNS_PORT, "*", apIP);   // every name -> the board

  const char* probes[] = {"/generate_204","/gen_204","/hotspot-detect.html","/ncsi.txt","/connecttest.txt","/canonical.html"};
  for (auto p : probes) http.on(p, redirectPortal);
  http.on("/", handleRoot);
  http.on("/admin", handleAdmin);
  http.onNotFound(handleNotFound);
  http.begin();

  Serial.printf("\n=== WEBHEAD PORTAL up ===  SSID \"%s\"  domain %s\n", AP_SSID, MY_DOMAIN);
  prompt();
}

void loop() {
  dnsServer.processNextRequest();
  http.handleClient();
  while (Serial.available()) {
    char ch = Serial.read();
    if (ch == '\r') continue;
    if (ch == '\n') { Serial.println(); runCmd(line); line = ""; prompt(); }
    else { line += ch; Serial.write(ch); }
  }
}
